In [69]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from pandas.api.types import is_numeric_dtype
from sklearn import preprocessing
from sklearn import tree
from sklearn.preprocessing import MinMaxScaler
import pydotplus 
import io
from IPython.display import Image
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score, f1_score, precision_score
#Scale large numbers from 0=1
#predict the class
#

In [70]:
german = pd.read_csv('german.data', header=None, sep = ' ')
wave = pd.read_csv('waveform.data')

In [71]:
german.columns = ["Status of existing checking account",
                "Duration in month",
                "Credit history",
                "Purpose",
                "Credit amount",
                "Savings account/bonds",
                "Present employment since",
                "Installment rate in percentage of disposable income",
                "Personal status and sex",
                "Other debtors / guarantors",
                "Present residence since",
                "Property",
                "Age in years",
                "Other installment plans",
                "Housing",
                "Number of existing credits at this bank",
                "Job",
                "Number of people being liable to provide maintenance for",
                "Telephone",
                "Foreign Worker",
                "Class"
               ]

In [72]:
wave.columns = ["1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "10",
                "11",
                "12",
                "13",
                "14",
                "15",
                "16",
                "17",
                "18",
                "19",
                "20",
                "21",
                "Class"
               ]

In [73]:
le = preprocessing.LabelEncoder()
for col in german.columns:
    if is_numeric_dtype(german[col]) == False:
        le.fit(german[col])
        german[col] = le.transform(german[col])

In [81]:
#normalize the Credit Amount
german['Credit amount'] = MinMaxScaler().fit_transform(np.array(german['Credit amount']).reshape(-1,1))
german.head()

,Status of existing checking account,Duration in month,Credit history,Purpose,Credit amount,Savings account/bonds,Present employment since,Installment rate in percentage of disposable income,Personal status and sex,Other debtors / guarantors,...,Property,Age in years,Other installment plans,Housing,Number of existing credits at this bank,Job,Number of people being liable to provide maintenance for,Telephone,Foreign Worker,Class
0,0,6,4,4,0.050567,4,4,4,2,0,...,0,67,2,1,2,2,1,1,0,1
1,1,48,2,4,0.313690,0,2,2,1,0,...,0,22,2,1,1,2,1,0,0,2
2,3,12,4,7,0.101574,0,3,2,2,0,...,0,49,2,1,1,1,2,0,0,1
3,0,42,2,3,0.419941,0,3,2,2,2,...,1,45,2,2,1,2,2,0,0,1
4,0,24,3,0,0.254209,0,2,3,2,0,...,3,53,2,2,2,2,2,0,0,2

In [82]:
Y = german['Class']
X = german.drop(['Class'],axis=1)

In [83]:
Ywave = wave['Class']
Xwave = wave.drop(['Class'],axis=1)

## Knn with n = 5 Minkowski Metrics

In [84]:
testAcc = []
testf = []
testp = []

testAccwave = []
testfwave = []
testpwave = []

for i in range(5):
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.1)
    Xwave_train, Xwave_test, Ywave_train, Ywave_test = train_test_split(Xwave, Ywave, test_size=0.1)
    
    clf = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
    clf.fit(X_train, Y_train)
    
    clfwave = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
    clfwave.fit(Xwave_train, Ywave_train)
    
    Y_predTest = clf.predict(X_test)
    Ywave_predTest = clfwave.predict(Xwave_test)
    
    testAcc.append(accuracy_score(Y_test, Y_predTest))
    testf.append(f1_score(Y_test, Y_predTest, average='weighted'))
    testp.append(precision_score(Y_test, Y_predTest,average= 'weighted'))
    
    testAccwave.append(accuracy_score(Ywave_test, Ywave_predTest))
    testfwave.append(f1_score(Ywave_test, Ywave_predTest, average='weighted'))
    testpwave.append(precision_score(Ywave_test, Ywave_predTest,average= 'weighted'))

## Knn Default Parameters

In [85]:
testAccd = []
testAccwaved = []

testfd = []
testfwaved = []

testpd = []
testpwaved = []

for i in range(5):
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.1)
    Xwave_train, Xwave_test, Ywave_train, Ywave_test = train_test_split(Xwave, Ywave, test_size=0.1)
    
    clf = KNeighborsClassifier()
    clf.fit(X_train, Y_train)
    
    clfwave = KNeighborsClassifier()
    clfwave.fit(Xwave_train, Ywave_train)
    
    Y_predTest = clf.predict(X_test)
    Ywave_predTest = clfwave.predict(Xwave_test)
    
    testAccd.append(accuracy_score(Y_test, Y_predTest))
    testfd.append(f1_score(Y_test, Y_predTest, average='weighted'))
    testpd.append(precision_score(Y_test, Y_predTest,average= 'weighted'))
    
    testAccwaved.append(accuracy_score(Ywave_test, Ywave_predTest))
    testfwaved.append(f1_score(Ywave_test, Ywave_predTest, average='weighted'))
    testpwaved.append(precision_score(Ywave_test, Ywave_predTest,average= 'weighted'))

## Compare

In [80]:
numNeighbors = [1, 5, 10, 15, 20, 25, 30]
for k in numNeighbors:
    clf = KNeighborsClassifier(n_neighbors=k, metric='minkowski', p=2)
    clf.fit(X_train, Y_train)
    Y_predTest = clf.predict(X_test)
    testAcc.append(accuracy_score(Y_test, Y_predTest))